/*
 *  Service related to token
 *
 */

export const getToken = () => {
  return "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDM3OTE2MzQsIm5iZiI6MTYwMzc5MTYzNCwianRpIjoiYjdkMzc2NTAtZTRjZS00ZDdhLThhOWEtZWY0NjdlZWI2ZTUyIiwiaWRlbnRpdHkiOnsiaWQiOiJhMDQwMTBkNy1hNmMxLTQ2YmQtYjk3Ni1lYzA4YWYxMGE1NzEiLCJlbWFpbCI6ImFkbWluQGFsdGFncmFtdGVzdC5jb20iLCJhY3RpdmUiOnRydWUsImZpcnN0X25hbWUiOiJQYXVsbyIsImxhc3RfbmFtZSI6IkJlbmF0dG8iLCJyb2xlcyI6eyJhZG1pbiI6e319LCJjcmVhdGVkX2F0IjoiMjAyMC0xMC0yNiAxNTowODoxNi4yMDAxMDgiLCJlbWFpbF9jb25maXJtZWRfYXQiOm51bGx9LCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.ZiIyWwBsuUgvenFQDv175gUiPpfUgXxkXlbWnPwryBg";
};
